### ISSUE TITLE
Trait-related error when loading code

### ISSUE THREAD

**Issue by girba** [activepapers/activepapers-pharo#1]
After getting a Pharo 7, and executing:

```
Metacello new
    baseline: 'ActivePapers';
    repository: 'github://activepapers/activepapers-pharo/src';
    load.
```

I get: 

```
UndefinedObject(Object)>>doesNotUnderstand: #asTraitComposition
MCClassDefinition>>traitCompositionCompiled
...
```

This seems due to `BaselineOfActivePapers` relying on a trait that is not in the same package:

```
Class {
	#name : #BaselineOfActivePapers,
	#superclass : #BaselineOf,
	#traits : 'TAPWiki',
	#classTraits : 'TAPWiki classTrait',
	#category : #BaselineOfActivePapers
}
```
https://github.com/activepapers/activepapers-pharo/blob/master/src/BaselineOfActivePapers/BaselineOfActivePapers.class.st

**Comment by khinsen** [comment]
Ouch. That's the second time I end up creating something interactively that then cannot be loaded from source code. Using my wiki in its own baseline was trying to be too clever :-(

**Comment by girba** [comment]
Reproducibility is not easy :).

**Comment by khinsen** [comment]
True - but live systems such as Pharo make it even more difficult!

Anyway, this is fixed by https://github.com/activepapers/activepapers-pharo/commit/e24cd00f89be589ffc340a9ca461cbfa220bdb85. Thanks for the quick report!
