### ISSUE TITLE
Failure to load in Pharo 7 on Mac

### ISSUE THREAD

**Issue by lukego** [activepapers/activepapers-pharo#2]
I started a Pharo 7 image from Pharo Launcher and tried running the Metacello command in the README. I got this error:

<img width="980" alt="Screenshot 2019-05-16 10 41 00" src="https://user-images.githubusercontent.com/13791/57839556-41f0ad00-77c7-11e9-9998-d982e08d9051.png">

I also tried loading in a recent GToolkit image but that had some kind of version conflict.

**Comment by khinsen** [comment]
This looks like a communication problem between your computer and GitHub. I suggest (1) verifying the Iceberg settings and (2) verifying your `ssh` configuration (keys etc.).

I have checked installation using an account other than my own (to make sure I access the repositories anonymously), and it works just fine.

**Comment by lukego** [comment]
OK but just to be clear this is a totally pristine Pharo 7 image and I have not touched any settings in Iceberg or anywhere else.

**Comment by khinsen** [comment]
It worked for me, on an account that did not have any configuration for `git` or `ssh`, with Pharo downloaded from http://get.pharo.org/64.
